In [1]:
import pandas as pd
import sqlite3

In [4]:
from google.colab import files
files.upload()

Saving future_product_store_dynamic_pricing.csv to future_product_store_dynamic_pricing.csv

{'future_product_store_dynamic_pricing.csv': b'date,product_id,store_id,category,region,predicted_demand,recommended_price,expected_revenue,holiday_promotion\n2026-01-09,P0001,S001,Electronics,North,133.02,54.88,7299.89,0\n2026-01-09,P0001,S002,Electronics,North,133.02,49.39,7299.39,0\n2026-01-09,P0001,S003,Electronics,North,133.02,56.68,7296.19,0\n2026-01-09,P0001,S004,Electronics,North,133.02,49.4,7301.51,0\n2026-01-09,P0001,S005,Electronics,North,133.02,53.18,7317.71,0\n2026-01-09,P0002,S001,Electronics,North,133.02,57.46,7396.3,0\n2026-01-09,P0002,S002,Electronics,North,133.02,51.89,7395.8,0\n2026-01-09,P0002,S003,Electronics,North,133.02,57.43,7392.55,0\n2026-01-09,P0002,S004,Electronics,North,133.02,61.18,7397.94,0\n2026-01-09,P0002,S005,Electronics,North,133.02,57.6,7414.36,0\n2026-01-09,P0003,S001,Electronics,North,133.02,53.38,7345.18,0\n2026-01-09,P0003,S002,Electronics,North,133.02,51.53,7344.68,0\n2026-01-09,P0003,S003,Electronics,North,133.02,51.51,7341.46,0\n2026-01-09,P0003,S004,Electronics,North,133.02,55.23,7346.81,0\n2026-01-09,P0003,S005,Electronics,North,133.02,60.89,7363.12,0\n2026-01-09,P0004,S001,Electronics,North,133.02,59.6,7432.6,0\n2026-01-09,P0004,S002,Electronics,North,133.02,57.73,7432.09,0\n2026-01-09,P0004,S003,Electronics,North,133.02,53.99,7428.84,0\n2026-01-09,P0004,S004,Electronics,North,133.02,50.3,7434.24,0\n2026-01-09,P0004,S005,Electronics,North,133.02,56.01,7450.75,0\n2026-01-09,P0005,S001,Electronics,North,133.02,51.67,7363.63,0\n2026-01-09,P0005,S002,Electronics,North,133.02,59.04,7363.13,0\n2026-01-09,P0005,S003,Electronics,North,133.02,59.02,7359.9,0\n2026-01-09,P0005,S004,Electronics,North,133.02,53.52,7365.26,0\n2026-01-09,P0005,S005,Electronics,North,133.02,61.04,7381.61,0\n2026-01-09,P0006,S001,Electronics,North,133.02,53.26,7329.34,0\n2026-01-09,P0006,S002,Electronics,North,133.02,53.26,7328.85,0\n2026-01-09,P0006,S003,Electronics,North,133.02,56.91,7325.63,0\n2026-01-09,P0006,S004,Electronics,North,133.02,55.11,7330.97,0\n2026-01-09,P0006,S005,Electronics,North,133.02,51.55,7347.24,0\n2026-01-09,P0007,S001,Electronics,North,133.02,60.78,7349.48,0\n2026-01-09,P0007,S002,Electronics,North,133.02,60.77,7348.99,0\n2026-01-09,P0007,S003,Electronics,North,133.02,51.54,7345.76,0\n2026-01-09,P0007,S004,Electronics,North,133.02,53.42,7351.11,0\n2026-01-09,P0007,S005,Electronics,North,133.02,59.08,7367.43,0\n2026-01-09,P0008,S001,Electronics,North,133.02,50.12,7407.23,0\n2026-01-09,P0008,S002,Electronics,North,133.02,53.82,7406.73,0\n2026-01-09,P0008,S003,Electronics,North,133.02,57.51,7403.48,0\n2026-01-09,P0008,S004,Electronics,North,133.02,59.41,7408.87,0\n2026-01-09,P0008,S005,Electronics,North,133.02,50.24,7425.32,0\n2026-01-09,P0009,S001,Electronics,North,133.02,57.34,7381.38,0\n2026-01-09,P0009,S002,Electronics,North,133.02,51.79,7380.88,0\n2026-01-09,P0009,S003,Electronics,North,133.02,61.01,7377.64,0\n2026-01-09,P0009,S004,Electronics,North,133.02,51.8,7383.01,0\n2026-01-09,P0009,S005,Electronics,North,133.02,55.63,7399.4,0\n2026-01-09,P0010,S001,Electronics,North,133.02,61.27,7408.78,0\n2026-01-09,P0010,S002,Electronics,North,133.02,53.84,7408.28,0\n2026-01-09,P0010,S003,Electronics,North,133.02,55.67,7405.03,0\n2026-01-09,P0010,S004,Electronics,North,133.02,53.85,7410.42,0\n2026-01-09,P0010,S005,Electronics,North,133.02,59.55,7426.87,0\n2026-01-09,P0011,S001,Electronics,North,133.02,62.45,7552.28,0\n2026-01-09,P0011,S002,Electronics,North,133.02,60.56,7551.77,0\n2026-01-09,P0011,S003,Electronics,North,133.02,56.75,7548.46,0\n2026-01-09,P0011,S004,Electronics,North,133.02,62.47,7553.95,0\n2026-01-09,P0011,S005,Electronics,North,133.02,58.81,7570.72,0\n2026-01-09,P0012,S001,Electronics,North,133.02,60.82,7355.2,0\n2026-01-09,P0012,S002,Electronics,North,133.02,49.76,7354.7,0\n2026-01-09,P0012,S003,Electronics,North,133.02,55.27,7351.48,0\n2026-01-09,P0012,S004,Electronics,North,133.02,55.31,7356.83,0\n2026-01-09,P0012,S005,Electronics,North,133.02,60.97,7373.16,0\n2026-01-09,P0013,S001,Electronics,North,133.02,55.4,7368.83,0\n2026-01-09,P0013,S002,Electronics,North,133.02,55.39,7368.33,0\n2026-01-09,P0013,S003,Electronics,North,133.02,53.52,7365.1,0\n2026-01-09,P0013,S004,Electronics,North,133.02,49.87,7370.47,0\n2026-01-09,P0013,S005,Electronics,North,133.02,51.83,7386.83,0\n2026-01-09,P0014,S001,Electronics,North,133.02,61.71,7462.39,0\n2026-01-09,P0014,S002,Electronics,North,133.02,59.83,7461.88,0\n2026-01-09,P0014,S003,Electronics,North,133.02,61.68,7458.61,0\n2026-01-09,P0014,S004,Electronics,North,133.02,50.5,7464.04,0\n2026-01-09,P0014,S005,Electronics,North,133.02,61.86,7480.61,0\n2026-01-09,P0015,S001,Electronics,North,133.02,60.61,7329.78,0\n2026-01-09,P0015,S002,Electronics,North,133.02,51.43,7329.29,0\n2026-01-09,P0015,S003,Electronics,North,133.02,53.24,7326.07,0\n2026-01-09,P0015,S004,Electronics,North,133.02,51.44,7331.41,0\n2026-01-09,P0015,S005,Electronics,North,133.02,57.08,7347.68,0\n2026-01-09,P0016,S001,Electronics,North,133.02,58.84,7337.99,0\n2026-01-09,P0016,S002,Electronics,North,133.02,51.48,7337.49,0\n2026-01-09,P0016,S003,Electronics,North,133.02,58.81,7334.28,0\n2026-01-09,P0016,S004,Electronics,North,133.02,60.69,7339.62,0\n2026-01-09,P0016,S005,Electronics,North,133.02,53.46,7355.91,0\n2026-01-09,P0017,S001,Electronics,North,133.02,60.47,7313.17,0\n2026-01-09,P0017,S002,Electronics,North,133.02,60.47,7312.67,0\n2026-01-09,P0017,S003,Electronics,North,133.02,49.45,7309.47,0\n2026-01-09,P0017,S004,Electronics,North,133.02,49.49,7314.79,0\n2026-01-09,P0017,S005,Electronics,North,133.02,60.62,7331.03,0\n2026-01-09,P0018,S001,Electronics,North,133.02,58.83,7336.0,0\n2026-01-09,P0018,S002,Electronics,North,133.02,55.14,7335.5,0\n2026-01-09,P0018,S003,Electronics,North,133.02,60.63,7332.29,0\n2026-01-09,P0018,S004,Electronics,North,133.02,53.32,7337.63,0\n2026-01-09,P0018,S005,Electronics,North,133.02,49.76,7353.92,0\n2026-01-09,P0019,S001,Electronics,North,133.02,51.72,7370.95,0\n2026-01-09,P0019,S002,Electronics,North,133.02,57.25,7370.44,0\n2026-01-09,P0019,S003,Electronics,North,133.02,49.85,7367.21,0\n2026-01-09,P0019,S004,Electronics,North,133.02,59.12,7372.58,0\n2026-01-09,P0019,S005,Electronics,North,133.02,61.1,7388.94,0\n2026-01-09,P0020,S001,Electronics,North,133.02,57.72,7430.6,0\n2026-01-09,P0020,S002,Electronics,North,133.02,61.44,7430.09,0\n2026-01-09,P0020,S003,Electronics,North,133.02,50.25,7426.84,0\n2026-01-09,P0020,S004,Electronics,North,133.02,61.46,7432.24,0\n2026-01-09,P0020,S005,Electronics,North,133.02,59.73,7448.74,0\n2026-01-10,P0001,S001,Electronics,North,133.02,49.39,7299.89,0\n2026-01-10,P0001,S002,Electronics,North,133.02,60.36,7299.39,0\n2026-01-10,P0001,S003,Electronics,North,133.02,51.19,7296.19,0\n2026-01-10,P0001,S004,Electronics,North,133.02,58.55,7301.51,0\n2026-01-10,P0001,S005,Electronics,North,133.02,49.51,7317.71,0\n2026-01-10,P0002,S001,Electronics,North,133.02,61.16,7396.3,0\n2026-01-10,P0002,S002,Electronics,North,133.02,61.16,7395.8,0\n2026-01-10,P0002,S003,Electronics,North,133.02,61.13,7392.55,0\n2026-01-10,P0002,S004,Electronics,North,133.02,53.76,7397.94,0\n2026-01-10,P0002,S005,Electronics,North,133.02,53.88,7414.36,0\n2026-01-10,P0003,S001,Electronics,North,133.02,49.7,7345.18,0\n2026-01-10,P0003,S002,Electronics,North,133.02,57.05,7344.68,0\n2026-01-10,P0003,S003,Electronics,North,133.02,58.87,7341.46,0\n2026-01-10,P0003,S004,Electronics,North,133.02,58.91,7346.81,0\n2026-01-10,P0003,S005,Electronics,North,133.02,49.82,7363.12,0\n2026-01-10,P0004,S001,Electronics,North,133.02,54.01,7432.6,0\n2026-01-10,P0004,S002,Electronics,North,133.02,61.46,7432.09,0\n2026-01-10,P0004,S003,Electronics,North,133.02,61.43,7428.84,0\n2026-01-10,P0004,S004,Electronics,North,133.02,50.3,7434.24,0\n2026-01-10,P0004,S005,Electronics,North,133.02,54.14,7450.75,0\n2026-01-10,P0005,S001,Electronics,North,133.02,51.67,7363.63,0\n2026-01-10,P0005,S002,Electronics,North,133.02,53.51,7363.13,0\n2026-01-10,P0005,S003,Electronics,North,133.02,49.8,7359.9,0\n2026-01-10,P0005,S004,Electronics,North,133.02,51.68,7365.26,0\n2026-01-10,P0005,S005,Electronics,North,133.02,61.04,7381.61,0\n2026-01-10,P0006,S001,Electronics,North,133.02,53.26,7329.34,0\n2026-01-10,P0006,S002,Electronics,North,133.02,53.26,7328.85,0\n2026-01-10,P0006,S003,Electronics,North,133.02,56.91,7325.63,0\n2026-01-10,P0006,S004,Electronics,North,133.02,49.6,7330.97,0\n2026-01-10,P0006,S005,Electronics,North,133.02,60.76,7347.24,0\n2026-01-10,P0007,S001,Electronics,North,133.02,57.09,7349.48,0\n2026-01-10,P0007,S002,Electronics,North,133.02,60.77,7348.99,0\n2026-01-10,P0007,S003,Electronics,North,133.02,49.7,7345.76,0\n2026-01-10,P0007,S004,Electronics,North,133.02,53.42,7351.11,0\n2026-01-10,P0007,S005,Electronics,North,133.02,55.38,7367.43,0\n2026-01-10,P0008,S001,Electronics,North,133.02,50.12,7407.23,0\n2026-01-10,P0008,S002,Electronics,North,133.02,51.97,7406.73,0\n2026-01-10,P0008,S003,Electronics,North,133.02,51.95,7403.48,0\n2026-01-10,P0008,S004,Electronics,North,133.02,55.7,7408.87,0\n2026-01-10,P0008,S005,Electronics,North,133.02,53.96,7425.32,0\n2026-01-10,P0009,S001,Electronics,North,133.02,49.94,7381.38,0\n2026-01-10,P0009,S002,Electronics,North,133.02,49.94,7380.88,0\n2026-01-10,P0009,S003,Electronics,North,133.02,61.01,7377.64,0\n2026-01-10,P0009,S004,Electronics,North,133.02,53.65,7383.01,0\n2026-01-10,P0009,S005,Electronics,North,133.02,57.48,7399.4,0\n2026-01-10,P0010,S001,Electronics,North,133.02,55.7,7408.78,0\n2026-01-10,P0010,S002,Electronics,North,133.02,55.69,7408.28,0\n2026-01-10,P0010,S003,Electronics,North,133.02,61.23,7405.03,0\n2026-01-10,P0010,S004,Electronics,North,133.02,61.28,7410.42,0\n2026-01-10,P0010,S005,Electronics,North,133.02,55.83,7426.87,0\n2026-01-10,P0011,S001,Electronics,North,133.02,58.67,7552.28,0\n2026-01-10,P0011,S002,Electronics,North,133.02,58.66,7551.77,0\n2026-01-10,P0011,S003,Electronics,North,133.02,60.53,7548.46,0\n2026-01-10,P0011,S004,Electronics,North,133.02,62.47,7553.95,0\n2026-01-10,P0011,S005,Electronics,North,133.02,62.6,7570.72,0\n2026-01-10,P0012,S001,Electronics,North,133.02,55.29,7355.2,0\n2026-01-10,P0012,S002,Electronics,North,133.02,60.82,7354.7,0\n2026-01-10,P0012,S003,Electronics,North,133.02,53.42,7351.48,0\n2026-01-10,P0012,S004,Electronics,North,133.02,55.31,7356.83,0\n2026-01-10,P0012,S005,Electronics,North,133.02,55.43,7373.16,0\n2026-01-10,P0013,S001,Electronics,North,133.02,49.86,7368.83,0\n2026-01-10,P0013,S002,Electronics,North,133.02,55.39,7368.33,0\n2026-01-10,P0013,S003,Electronics,North,133.02,60.9,7365.1,0\n2026-01-10,P0013,S004,Electronics,North,133.02,51.71,7370.47,0\n2026-01-10,P0013,S005,Electronics,North,133.02,61.08,7386.83,0\n2026-01-10,P0014,S001,Electronics,North,133.02,59.84,7462.39,0\n2026-01-10,P0014,S002,Electronics,North,133.02,54.23,7461.88,0\n2026-01-10,P0014,S003,Electronics,North,133.02,50.46,7458.61,0\n2026-01-10,P0014,S004,Electronics,North,133.02,52.37,7464.04,0\n2026-01-10,P0014,S005,Electronics,North,133.02,52.49,7480.61,0\n2026-01-10,P0015,S001,Electronics,North,133.02,51.43,7329.78,0\n2026-01-10,P0015,S002,Electronics,North,133.02,58.77,7329.29,0\n2026-01-10,P0015,S003,Electronics,North,133.02,49.57,7326.07,0\n2026-01-10,P0015,S004,Electronics,North,133.02,49.6,7331.41,0\n2026-01-10,P0015,S005,Electronics,North,133.02,49.71,7347.68,0\n2026-01-10,P0016,S001,Electronics,North,133.02,55.16,7337.99,0\n2026-01-10,P0016,S002,Electronics,North,133.02,49.64,7337.49,0\n2026-01-10,P0016,S003,Electronics,North,133.02,56.97,7334.28,0\n2026-01-10,P0016,S004,Electronics,North,133.02,53.34,7339.62,0\n2026-01-10,P0016,S005,Electronics,North,133.02,53.46,7355.91,0\n2026-01-10,P0017,S001,Electronics,North,133.02,60.47,7313.17,0\n2026-01-10,P0017,S002,Electronics,North,133.02,60.47,7312.67,0\n2026-01-10,P0017,S003,Electronics,North,133.02,49.45,7309.47,0\n2026-01-10,P0017,S004,Electronics,North,133.02,60.49,7314.79,0\n2026-01-10,P0017,S005,Electronics,North,133.02,51.44,7331.03,0\n2026-01-10,P0018,S001,Electronics,North,133.02,55.15,7336.0,0\n2026-01-10,P0018,S002,Electronics,North,133.02,60.66,7335.5,0\n2026-01-10,P0018,S003,Electronics,North,133.02,56.96,7332.29,0\n2026-01-10,P0018,S004,Electronics,North,133.02,57.0,7337.63,0\n2026-01-10,P0018,S005,Electronics,North,133.02,57.13,7353.92,0\n2026-01-10,P0019,S001,Electronics,North,133.02,55.41,7370.95,0\n2026-01-10,P0019,S002,Electronics,North,133.02,57.25,7370.44,0\n2026-01-10,P0019,S003,Electronics,North,133.02,53.54,7367.21,0\n2026-01-10,P0019,S004,Electronics,North,133.02,51.73,7372.58,0\n2026-01-10,P0019,S005,Electronics,North,133.02,49.99,7388.94,0\n2026-01-10,P0020,S001,Electronics,North,133.02,61.45,7430.6,0\n2026-01-10,P0020,S002,Electronics,North,133.02,50.27,7430.09,0\n2026-01-10,P0020,S003,Electronics,North,133.02,61.41,7426.84,0\n2026-01-10,P0020,S004,Electronics,North,133.02,55.87,7432.24,0\n2026-01-10,P0020,S005,Electronics,North,133.02,59.73,7448.74,0\n2026-01-11,P0001,S001,Electronics,North,133.02,51.22,7299.89,0\n2026-01-11,P0001,S002,Electronics,North,133.02,54.87,7299.39,0\n2026-01-11,P0001,S003,Electronics,North,133.02,56.68,7296.19,0\n2026-01-11,P0001,S004,Electronics,North,133.02,49.4,7301.51,0\n2026-01-11,P0001,S005,Electronics,North,133.02,53.18,7317.71,0\n2026-01-11,P0002,S001,Electronics,North,133.02,50.04,7396.3,0\n2026-01-11,P0002,S002,Electronics,North,133.02,53.74,7395.8,0\n2026-01-11,P0002,S003,Electronics,North,133.02,61.13,7392.55,0\n2026-01-11,P0002,S004,Electronics,North,133.02,55.61,7397.94,0\n2026-01-11,P0002,S005,Electronics,North,133.02,61.31,7414.36,0\n2026-01-11,P0003,S001,Electronics,North,133.02,49.7,7345.18,0\n2026-01-11,P0003,S002,Electronics,North,133.02,49.69,7344.68,0\n2026-01-11,P0003,S003,Electronics,North,133.02,49.67,7341.46,0\n2026-01-11,P0003,S004,Electronics,North,133.02,49.71,7346.81,0\n2026-01-11,P0003,S005,Electronics,North,133.02,59.04,7363.12,0\n2026-01-11,P0004,S001,Electronics,North,133.02,50.29,7432.6,0\n2026-01-11,P0004,S002,Electronics,North,133.02,50.28,7432.09,0\n2026-01-11,P0004,S003,Electronics,North,133.02,59.57,7428.84,0\n2026-01-11,P0004,S004,Electronics,North,133.02,52.16,7434.24,0\n2026-01-11,P0004,S005,Electronics,North,133.02,54.14,7450.75,0\n2026-01-11,P0005,S001,Electronics,North,133.02,53.51,7363.63,0\n2026-01-11,P0005,S002,Electronics,North,133.02,60.89,7363.13,0\n2026-01-11,P0005,S003,Electronics,North,133.02,55.33,7359.9,0\n2026-01-11,P0005,S004,Electronics,North,133.02,57.21,7365.26,0\n2026-01-11,P0005,S005,Electronics,North,133.02,53.64,7381.61,0\n2026-01-11,P0006,S001,Electronics,North,133.02,60.61,7329.34,0\n2026-01-11,P0006,S002,Electronics,North,133.02,58.77,7328.85,0\n2026-01-11,P0006,S003,Electronics,North,133.02,49.56,7325.63,0\n2026-01-11,P0006,S004,Electronics,North,133.02,51.44,7330.97,0\n2026-01-11,P0006,S005,Electronics,North,133.02,49.71,7347.24,0\n2026-01-11,P0007,S001,Electronics,North,133.02,60.78,7349.48,0\n2026-01-11,P0007,S002,Electronics,North,133.02,49.72,7348.99,0\n2026-01-11,P0007,S003,Electronics,North,133.02,60.74,7345.76,0\n2026-01-11,P0007,S004,Electronics,North,133.02,55.26,7351.11,0\n2026-01-11,P0007,S005,Electronics,North,133.02,53.54,7367.43,0\n2026-01-11,P0008,S001,Electronics,North,133.02,53.83,7407.23,0\n2026-01-11,P0008,S002,Electronics,North,133.02,59.39,7406.73,0\n2026-01-11,P0008,S003,Electronics,North,133.02,53.8,7403.48,0\n2026-01-11,P0008,S004,Electronics,North,133.02,57.55,7408.87,0\n2026-01-11,P0008,S005,Electronics,North,133.02,50.24,7425.32,0\n2026-01-11,P0009,S001,Electronics,North,133.02,53.64,7381.38,0\n2026-01-11,P0009,S002,Electronics,North,133.02,59.19,7380.88,0\n2026-01-11,P0009,S003,Electronics,North,133.02,53.61,7377.64,0\n2026-01-11,P0009,S004,Electronics,North,133.02,49.95,7383.01,0\n2026-01-11,P0009,S005,Electronics,North,133.02,53.77,7399.4,0\n2026-01-11,P0010,S001,Electronics,North,133.02,50.13,7408.78,0\n2026-01-11,P0010,S002,Electronics,North,133.02,61.26,7408.28,0\n2026-01-11,P0010,S003,Electronics,North,133.02,50.1,7405.03,0\n2026-01-11,P0010,S004,Electronics,North,133.02,59.42,7410.42,0\n2026-01-11,P0010,S005,Electronics,North,133.02,61.42,7426.87,0\n2026-01-11,P0011,S001,Electronics,North,133.02,56.77,7552.28,0\n2026-01-11,P0011,S002,Electronics,North,133.02,58.66,7551.77,0\n2026-01-11,P0011,S003,Electronics,North,133.02,56.75,7548.46,0\n2026-01-11,P0011,S004,Electronics,North,133.02,62.47,7553.95,0\n2026-01-11,P0011,S005,Electronics,North,133.02,60.71,7570.72,0\n2026-01-11,P0012,S001,Electronics,North,133.02,53.45,7355.2,0\n2026-01-11,P0012,S002,Electronics,North,133.02,55.29,7354.7,0\n2026-01-11,P0012,S003,Electronics,North,133.02,58.95,7351.48,0\n2026-01-11,P0012,S004,Electronics,North,133.02,49.77,7356.83,0\n2026-01-11,P0012,S005,Electronics,North,133.02,60.97,7373.16,0\n2026-01-11,P0013,S001,Electronics,North,133.02,57.24,7368.83,0\n2026-01-11,P0013,S002,Electronics,North,133.02,49.85,7368.33,0\n2026-01-11,P0013,S003,Electronics,North,133.02,49.83,7365.1,0\n2026-01-11,P0013,S004,Electronics,North,133.02,60.95,7370.47,0\n2026-01-11,P0013,S005,Electronics,North,133.02,49.98,7386.83,0\n2026-01-11,P0014,S001,Electronics,North,133.02,50.49,7462.39,0\n2026-01-11,P0014,S002,Electronics,North,133.02,59.83,7461.88,0\n2026-01-11,P0014,S003,Electronics,North,133.02,54.2,7458.61,0\n2026-01-11,P0014,S004,Electronics,North,133.02,61.72,7464.04,0\n2026-01-11,P0014,S005,Electronics,North,133.02,56.24,7480.61,0\n2026-01-11,P0015,S001,Electronics,North,133.02,60.61,7329.78,0\n2026-01-11,P0015,S002,Electronics,North,133.02,58.77,7329.29,0\n2026-01-11,P0015,S003,Electronics,North,133.02,60.58,7326.07,0\n2026-01-11,P0015,S004,Electronics,North,133.02,55.11,7331.41,0\n2026-01-11,P0015,S005,Electronics,North,133.02,57.08,7347.68,0\n2026-01-11,P0016,S001,Electronics,North,133.02,60.68,7337.99,0\n2026-01-11,P0016,S002,Electronics,North,133.02,51.48,7337.49,0\n2026-01-11,P0016,S003,Electronics,North,133.02,56.97,7334.28,0\n2026-01-11,P0016,S004,Electronics,North,133.02,51.5,7339.62,0\n2026-01-11,P0016,S005,Electronics,North,133.02,58.98,7355.91,0\n2026-01-11,P0017,S001,Electronics,North,133.02,51.31,7313.17,0\n2026-01-11,P0017,S002,Electronics,North,133.02,58.64,7312.67,0\n2026-01-11,P0017,S003,Electronics,North,133.02,54.95,7309.47,0\n2026-01-11,P0017,S004,Electronics,North,133.02,51.32,7314.79,0\n2026-01-11,P0017,S005,Electronics,North,133.02,58.79,7331.03,0\n2026-01-11,P0018,S001,Electronics,North,133.02,55.15,7336.0,0\n2026-01-11,P0018,S002,Electronics,North,133.02,51.47,7335.5,0\n2026-01-11,P0018,S003,Electronics,North,133.02,53.28,7332.29,0\n2026-01-11,P0018,S004,Electronics,North,133.02,53.32,7337.63,0\n2026-01-11,P0018,S005,Electronics,North,133.02,60.81,7353.92,0\n2026-01-11,P0019,S001,Electronics,North,133.02,60.95,7370.95,0\n2026-01-11,P0019,S002,Electronics,North,133.02,49.87,7370.44,0\n2026-01-11,P0019,S003,Electronics,North,133.02,51.69,7367.21,0\n2026-01-11,P0019,S004,Electronics,North,133.02,60.97,7372.58,0\n2026-01-11,P0019,S005,Electronics,North,133.02,49.99,7388.94,0\n2026-01-11,P0020,S001,Electronics,North,133.02,61.45,7430.6,0\n2026-01-11,P0020,S002,Electronics,North,133.02,55.86,7430.09,0\n2026-01-11,P0020,S003,Electronics,North,133.02,55.83,7426.84,0\n2026-01-11,P0020,S004,Electronics,North,133.02,54.01,7432.24,0\n2026-01-11,P0020,S005,Electronics,North,133.02,57.86,7448.74,0\n2026-01-12,P0001,S001,Electronics,North,133.02,49.39,7299.89,0\n2026-01-12,P0001,S002,Electronics,North,133.02,58.53,7299.39,0\n2026-01-12,P0001,S003,Electronics,North,133.02,58.51,7296.19,0\n2026-01-12,P0001,S004,Electronics,North,133.02,49.4,7301.51,0\n2026-01-12,P0001,S005,Electronics,North,133.02,51.34,7317.71,0\n2026-01-12,P0002,S001,Electronics,North,133.02,55.6,7396.3,0\n2026-01-12,P0002,S002,Electronics,North,133.02,50.04,7395.8,0\n2026-01-12,P0002,S003,Electronics,North,133.02,59.28,7392.55,0\n2026-01-12,P0002,S004,Electronics,North,133.02,50.05,7397.94,0\n2026-01-12,P0002,S005,Electronics,North,133.02,61.31,7414.36,0\n2026-01-12,P0003,S001,Electronics,North,133.02,55.22,7345.18,0\

In [5]:
df_pricing = pd.read_csv("future_product_store_dynamic_pricing.csv")
df_pricing.head()

,date,product_id,store_id,category,region,predicted_demand,recommended_price,expected_revenue,holiday_promotion
0,2026-01-09,P0001,S001,Electronics,North,133.02,54.88,7299.89,0
1,2026-01-09,P0001,S002,Electronics,North,133.02,49.39,7299.39,0
2,2026-01-09,P0001,S003,Electronics,North,133.02,56.68,7296.19,0
3,2026-01-09,P0001,S004,Electronics,North,133.02,49.40,7301.51,0
4,2026-01-09,P0001,S005,Electronics,North,133.02,53.18,7317.71,0

In [6]:
conn = sqlite3.connect("retail_pricing.db")
cursor = conn.cursor()

In [7]:
df_pricing.to_sql(
    "future_pricing_recommendations",
    conn,
    if_exists="replace",
    index=False
)

1400

In [8]:
#price for product in a store
query = """
SELECT date, product_id, store_id, recommended_price
FROM future_pricing_recommendations
WHERE product_id = 'P001'
  AND store_id = 'S001'
ORDER BY date;
"""
pd.read_sql(query, conn)

Empty DataFrame
Columns: [date, product_id, store_id, recommended_price]
Index: []

In [9]:
#category wise average price
query = """
SELECT category, AVG(recommended_price) AS avg_price
FROM future_pricing_recommendations
WHERE holiday_promotion = 1
GROUP BY category;
"""
pd.read_sql(query, conn)

Empty DataFrame
Columns: [category, avg_price]
Index: []

In [10]:
#Region-wise pricing insight
query = """
SELECT region, AVG(recommended_price) AS avg_price
FROM future_pricing_recommendations
GROUP BY region;
"""
pd.read_sql(query, conn)

  region  avg_price
0  North  55.555057

In [11]:
conn.close()